name: Publish

on:
  release:
    types:
      - published

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          # token: ${{ secrets.RELEASE_PAT_TOKEN }}
      - name: Update root package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ github.event.release.tag_name }}
      - name: Update laskakit-data-feeder package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: laskakit-data-feeder/package.json
          field: version
          value: ${{ github.event.release.tag_name }}
      - name: Update laskakit-data-feeder addon config.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: laskakit-data-feeder/config.json
          field: version
          value: ${{ github.event.release.tag_name }}
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update to version ${{ github.event.release.tag_name }} [skip ci]"

  publish-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - update-versions
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker Hub
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target laskakit-data-feeder \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}

  update-add-ons-repository:
    name: 📢 Publish Add-on in Homeassistant
    runs-on: ubuntu-latest
    needs:
     - publish-docker
    steps:
      - name: 🚀 Dispatch Repository Updater update signal
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.HA_DISPATCH_TOKEN }}
          repository: radoslavirha/homeassistant-addons
          event-type: update
          client-payload: '{"addon": "laskakit-data-feeder"}'
